name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repositoryni yuklash
        uses: actions/checkout@v3

      - name: Flutterni o‘rnatish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Pub dependencies yuklash
        run: flutter pub get

      - name: Unit testlarni ishlatish
        run: flutter test || true

      - name: Build qilish (Android)
        run: flutter build apk --release

